name: SWATTR Reproduction

on:
  release:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  evaluate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        similarity: [50, 75, 80, 100]
        case_study: [TS, TM, MS]
        include:
          - case_study: TS
            model: teastore/model/teastore.owl
            text: teastore/text/EcsaText.txt
          - case_study: TM
            model: teammates/model/teammates.owl
            text: teammates/text/TeammatesForEvalText.txt
          - case_study: MS
            model: mediastore/models/mediastore.owl
            text: mediastore/text/Palladio_MediaStore_Text.txt
          - similarity: 50
            sim_score: 0.5
          - similarity: 75
            sim_score: 0.75
          - similarity: 80
            sim_score: 0.80
          - similarity: 100
            sim_score: 1            
            
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 16
       
    - name: Build / Install Parent
      run: cd swattr_parent && mvn clean install
      
    - name: Build SWATTR
      run: cd swattr_core && mvn package
        
    - name: Show Reproduction Directory and set similarity
      working-directory: reproduction
      run: echo "similarityPercentage=${{ matrix.sim_score }}" > config.properties && ls -l
    - name: Evaluate SWATTR
      working-directory: reproduction
      run: java --illegal-access=permit -jar ../swattr_core/pipeline/target/ardoco-core-pipeline.jar -n "${{ matrix.case_study }}" -m "../case_studies/${{ matrix.model }}" -t "../case_studies/${{ matrix.text }}" -c config.properties -o "swattr_results_${{ matrix.similarity }}_${{ matrix.case_study }}"
       
    - name: Save SWATTR Results
      uses: actions/upload-artifact@v2
      with:
        name: "swattr_results_${{ matrix.similarity }}_${{ matrix.case_study }}"
        path: "reproduction/swattr_results_${{ matrix.similarity }}_${{ matrix.case_study }}"
    
  aggregate:
    runs-on: ubuntu-latest
    needs: evaluate
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: evaluated-data
        
    - name: Structure Data
      working-directory: evaluated-data
      run: cp ../.github/.workflows/extract-data.sh . && bash extract-data.sh 
      
    - name: Evaluate Precision, Recall, F1
      working-directory: evaluated-data
      run: python -m pip install --upgrade pip && pip install -r ../eval/requirements.txt && cp ../.github/.workflows/evaluate.sh . && bash evaluate.sh
      
    - name: Save Evaluation Results
      uses: actions/upload-artifact@v2
      with:
        name: "Evaluation_SWATTR"
        path: "evaluated-data/results"
